config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"

  resources :items do
    collection do
      get 'up'
      get 'down'
    end
  end

  resources :categories do
    collection do
      get 'up'
      get 'down'
    end
  end

  resources :quotes do
    member do
      get 'send_or_back'
      get 'preview'
      post 'send_quote'
    end
  end

  resources :profiles

  resources :users


  get 'signup' => 'users#new', as: :signup

  post 'register' => 'users#create', as: :register

  get 'login' => 'sessions#new', as: :login

  post 'logout' => 'sessions#destroy', as: :logout

  resources :sessions

  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  post 'forgot_password_send' => 'users#forgot_password_send', as: :forgot_password_send
  get 'reset_password' => 'users#forgot_password_new', as: :reset_password
  post 'forgot_password_change' => 'users#forgot_password_change'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/quotes_controller.rb
# coding: utf-8
class QuotesController < ApplicationController
  before_action :setup_nav, :admin_required
  before_action :find_quote, only: [:preview, :send_quote, :destroy]

  VAT_RATE = 20
  
  def index
    @quotes = @current_profile.quotes
  end
  
  def new
  end
  
  def create
    @quote = Quote.new
    @quote.profile_id = @current_profile.id

    # update profile default introduction
    @current_profile.intro = params[:introduction]
    @current_profile.save

    incorrect = 'The quote form was not filled out correctly: '

    if params[:title].empty?
      flash.now[:notice] = incorrect + 'A title must be specified'
      render :action => 'quote_help' and return
    elsif params[:reference].empty?
      flash.now[:notice] = incorrect + 'A quote reference must be specified'
      render :action => 'quote_help' and return
    elsif params[:to].empty?
      flash.now[:notice] = incorrect + 'A recipient must be specified'
      render :action => 'quote_help' and return
    elsif params[:carriage].empty?
      flash.now[:notice] = incorrect + 'Carriage must be specified. Enter 0 for no carriage.'
      render :action => 'quote_help' and return
    end

    @quote.title = params[:title]
    @quote.reference = params[:reference]
    @quote.to = params[:to]
    @quote.cc = params[:cc]

    @sub_total = 0.00
    @details = ''

    q = ''

    q += '<p><strong>' + @quote.title
    q += ' (Quotation number: ' + @quote.reference + ')</strong></p>'
    q += "\n<table id=\"quote\">\n"
	  q += "<tr><th class=\"qty\">Qty</th><th class=\"name\">Description</th>"
	  q += "<th class=\"unitprice\">Unit Price</th><th class=\"amount\">Amount</th></tr>\n"

  	if params[:items]
  		params[:items].each_pair do |item_id, qty|
  		  qty = qty.to_f
  		  unless qty == 0
  		    item = Item.find(item_id)
					q += quote_line(item.name, item.price_in_pounds.to_f, qty)
					unless item.information.empty?
					  @details += "\n\n<h2>" + item.name + "</h2>\n"
					  @details += item.information
				  end
  			end
  		end
  	end
  	
  	# extra items
  	params[:x_qty].length.times do |i|
  	  i = i.to_s
  	  begin
  	    x_qty = params[:x_qty][i].to_f
  	    x_name = params[:x_name][i]
  	    x_price = params[:x_price][i]
  	    x_price.gsub!(/[,£]/,'')
  	    x_price = x_price.to_f
  	    if x_qty != 0
          q += quote_line(x_name, x_price, x_qty)
        end
	    rescue
	      next
      end
	  end

    unless params[:carriage] == "0"
      q += quote_line('Carriage', params[:carriage].to_f, 1)
    end

  	vat = @sub_total * (VAT_RATE.to_f / 100)
    
  	q += "<tr><td class=\"subempty\"></td><td class=\"subempty\"></td><td class=\"subtotallabel\">"
  	q += "Sub-total</td><td class=\"subtotal\">" + money(@sub_total) + "</td></tr>\n"
  	q += "<tr><td class=\"empty\"></td>"
  	if @current_profile.vat_number.empty?
  	  q += "<td class=\"empty\">"
  	else
  	  q += "<td class=\"vatno\">VAT No " + @current_profile.vat_number
  	end
  	q += "</td>"
  	q += "<td>VAT " + VAT_RATE.to_s + "%</td><td class=\"vat\">" + money(vat) + "</td></tr>\n"
  	total = @sub_total + vat
  	q += "<tr><td class=\"empty\"></td><td class=\"empty\"></td><td class=\"totallabel\">Total</td>"
  	q += "<td class=\"total\">" + money(total) + "</td></tr>\n"
  	q += "</table>\n"

    body = @current_profile.html
    body.gsub!('[quote]', q)
    body.gsub!('[introduction]', params[:introduction])
    body.gsub!('[details]', @details)
    body.gsub!('[reference]', @quote.reference)
    body.gsub!('[to]', @quote.to)
    body.gsub!('[total]', total.to_s)

    @quote.body = body
    @quote.save
  end

  def preview
    render :action => 'preview', :layout => false
  end
  
  def send_quote
    generate_pdf
    Emailer.quote(@quote, @current_profile.from, file_for_quote('pdf')).deliver
    @quote.sent_at = Time.now
    @quote.save
    flash[:notice] = 'Quote sent'
    redirect_to :action => 'index'
  end

  def destroy
    @quote.destroy
    flash[:notice] = 'Quote deleted.'
    redirect_to quotes_url
  end
  
  private

  def file_for_quote ext
    File::join(Rails.root, 'pdf', 'html_tmp', 'quote' + @quote.id.to_s + '.' + ext)
  end

  def generate_pdf
    html = file_for_quote 'html'
    f = File.new(html, 'w')
    f.puts @quote.body
    f.close

    dompdf = File::join(Rails.root, 'pdf', 'dompdf-0.5.1', 'dompdf.php')
    cmd = "php #{dompdf} -p a4 #{html}"
    system(cmd)
  end

  def money(money)
  	money *= 100
  	money = money.ceil
  	money /= 100.0
  	sprintf("%01.2f", money)
  end

  def quote_line(name, unit_price, quantity=1)
    display_qty = quantity.to_s
    if display_qty[-2,2] == '.0'
      display_qty = display_qty[0,display_qty.length-2]
    end
  	line = ''

  	line += '<tr><td class="qty">' + display_qty + '</td>'
  	line += '<td class="name">' + name + '</td>'
  	line += '<td class="unitprice">'
  	if(unit_price == 0)
  	  line += 'FOC'
  	else
  	  line += money(unit_price)
	  end
  	line += '</td>'
  	amount = unit_price * quantity
  	line += '<td class="amount">' + money(amount) + '</td>'
  	line += "</tr>\n"
  	@sub_total += amount

  	line
  end

  def setup_nav
    @nav = 'quotes'
  end

  def find_quote
    @quote = Quote.find(params[:id])
  end
end

app/views/quotes/_quote.html.erb
<% cache(quote) do -%>
<tr>
  <td><%= link_to quote.title, action: 'preview', id: quote %></td>
  <td><%= quote.to %></td>
  <td><%= format_date(quote.sent_at) %></td>
  <td class="actions"><%= delete_button(quote) %></td>
</tr>
<% end -%>

app/views/quotes/create.html.erb
<%= form_tag(send_quote_quote_path(@quote), class: 'pure-form') do %>
  <input type="hidden" name="id" value="<%= @quote.id %>" />
  <input type="button" onclick="history.back()" value="Make Changes" class="pure-button">
  <%= submit_tag 'Send', class: 'pure-button pure-button-primary' %>
<% end %>

<iframe src="/quotes/<%= @quote.id %>/preview"></iframe>

app/views/quotes/index.html.erb
<p><%= link_to 'New quote', new_quote_path, class: 'pure-button pure-button-primary' %></p>

<% unless @quotes.empty? -%>
<table class="pure-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Recipient</th>
      <th>Sent</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'quote', collection: @quotes %>
  </tbody>
</table>
<% else -%>
<p>No quotes have been sent yet.</p>
<% end %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= form_tag({action: 'create'}, {class: 'pure-form'}) do %>
  <p>
    <label for="title">Title:</label><br />
    <input type="text" id="title" name="title" value="<%= @current_profile.subject %>">
  </p>
  <p>
    <label for="reference">Reference:</label><br />
    <input type="text" id="reference" name="reference" />
  </p>
  <p>
    <label for="to">Send email to:</label><br />
    <input type="text" id="to" name="to" />
  </p>
  <p>
    <label for="cc">Cc:</label><br />
    <input type="text" id="cc" name="cc" />
  </p>
  <p>
    <label for="introduction">Introduction:</label><br />
    <textarea id="introduction" name="introduction"><%= @current_profile.intro %></textarea>
  </p>
  <h2>Items to Include</h2>
  <% @current_profile.categories.each do |category| %>
  <h3><%= category.name %></h3>
  <% category.items.each do |item| %>
  <p class="item_list">
    <input type="text" class="qty" name="items[<%= item.id %>]" value="0"> &times; <%= item.name %> (£<%= item.price_in_pounds %>)
  </p>
  <% end %>
  <% end %>
  <h2>Additional Items</h2>
  <% 10.times do |i| -%>
  <p class="item_list">
    <input type="text" class="qty" name="x_qty[<%= i %>]" value="0" /> &times;
    <input type="text" class="x_name" name="x_name[<%= i %>]" /> @
    £<input type="text" class="price" name="x_price[<%= i %>]" /> each
  </p>
  <% end -%>
  <p>
    <label for="cc">Carriage:</label><br />
    £<input type="text" id="carriage" name="carriage" class="price" />
  </p>
  <%= submit_tag 'Preview', class: 'pure-button pure-button-primary' %>
<% end %>

app/views/quotes/preview.html.erb
<%= raw @quote.body %>

app/views/quotes/quote_help.html.erb
<h1>Oops</h1>

<input type="button" onclick="history.back()" value="Make Changes" class="pure-button">