config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"

  resources :items do
    collection do
      get 'up'
      get 'down'
    end
  end

  resources :categories do
    collection do
      get 'up'
      get 'down'
    end
  end

  resources :quotes do
    member do
      get 'send_or_back'
      get 'preview'
      post 'send_quote'
    end
  end

  resources :profiles

  resources :users


  get 'signup' => 'users#new', as: :signup

  post 'register' => 'users#create', as: :register

  get 'login' => 'sessions#new', as: :login

  post 'logout' => 'sessions#destroy', as: :logout

  resources :sessions

  get 'forgot_password' => 'users#forgot_password', as: :forgot_password
  post 'forgot_password_send' => 'users#forgot_password_send', as: :forgot_password_send
  get 'reset_password' => 'users#forgot_password_new', as: :reset_password
  post 'forgot_password_change' => 'users#forgot_password_change'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=720" />
  <title>Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="layout" class="pure-g">
  <div class="pure-u-1 pure-u-med-1-4">
    <p>
      <%= link_to 'Quotes', quotes_path, class: 'pure-button' %>
      <%= link_to 'Categories', categories_path, class: 'pure-button' %>
      <%= link_to 'Items', items_path, class: 'pure-button' %>
    </p>
  </div>
  <div class="pure-u-1 pure-u-med-3-4">
    <div id="logo"><img src="/images/<%= @current_profile.domain %>.logo.png" alt="Logo" /></div>
    <%= flash_notice %>
    <%= yield %>
    <% if @current_user %>
      <p id="sign_out"><%= link_to 'Sign out', logout_path, method: :post %></p>
    <% end %>
  </div>
</div><!--#layout-->
</body>
</html>